window.onload = function() {
    var source = document.getElementById("records-template").innerHTML;
    var template = Handlebars.compile(source);
    var data = {
        records: [ {
            map: "Aardvark",
            slug: "aardvark",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Abandoned Canyon",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Abandoned Dam",
            slug: "abandoned-dam",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Actrix",
            slug: "actrix",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Actrix TE",
            slug: "actrix-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ambush TE",
            slug: "ambush-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ancient Lake",
            slug: "ancient-lake",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arc",
            slug: "arc",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arcadia TE",
            slug: "arcadia-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arizona",
            slug: "arizona",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arkashia",
            slug: "arkashia",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arriva",
            slug: "arriva",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Asylum",
            slug: "asylum",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Atlantis",
            slug: "atlantis",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Audax",
            slug: "audax",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Aura",
            slug: "aura",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Babylon Gardens",
            slug: "babylon-gardens",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Bleened Rings",
            slug: "bleened-rings",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Block Fort",
            slug: "block-fort",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Bob-omb Battlefield",
            slug: "bob-omb-battlefield",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boolean 1",
            slug: "boolean-1",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boolean Classic",
            slug: "boolean-classic",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boolean TE",
            slug: "boolean-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Borone CTF",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Borone KOTH",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boundaries TE",
            slug: "boundaries-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Broken World",
            slug: "broken-world",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Camel",
            slug: "camel",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Campfire",
            slug: "campfire",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Campi Erbosi 2",
            slug: "campi-erbosi-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Campus",
            slug: "campus",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Candyland",
            slug: "candyland",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Canyon",
            slug: "canyon",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Castella",
            slug: "castella",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Castle Adventure",
            slug: "castle-adventure",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Castle Adventure TE",
            slug: "castle-adventure-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Castle In The Rocks",
            slug: "castle-in-the-rocks",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Cavum",
            slug: "cavum",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Cavum 2",
            slug: "cavum-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Cheaghalov Station",
            slug: "cheaghalov-station",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "CherrylandMC",
            slug: "cherrylandmc",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Chimeric",
            slug: "chimeric",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "ChimericIIITrio",
            slug: "chimericiiitrio",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Chowder",
            slug: "chowder",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "City Scape",
            slug: "city-scape",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Civilization",
            slug: "civilization",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Clay Wars",
            slug: "clay-wars",
            game_mode: "DTM",
            record_first: [ { player_name: "Dunkel", player_uuid: "43276bd0-7483-4607-bbde-5ab27ee173b3", distance: "27.07", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Clearmont",
            slug: "clearmont",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Clearnmont 2",
            slug: "clearmont-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Cobweb Hills",
            slug: "cobweb-hills",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "ColorExplosion",
            slug: "colorexplosion",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Coniculum",
            slug: "coniculum",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Crescent: Subtle",
            slug: "crescent-subtle",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Crossfire TE",
            slug: "crossfire-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Cruhan",
            slug: "cruhan",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Curabitur",
            slug: "curabitur",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Daisy",
            slug: "daisy",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Deathlands",
            slug: "deathlands",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Decay",
            slug: "decay",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Destroyed Cave",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dirilis",
            slug: "dirilis",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dragonblaze Peaks",
            slug: "dragonblaze-peaks",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dragons Den",
            slug: "dragons-den",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dredmor",
            slug: "dredmor",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Drought Stand",
            slug: "drought-stand",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Drystep",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dust Devils",
            slug: "dust-devils",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dust Devils AvD",
            slug: "dust-devils-avd",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dustdrive",
            slug: "dustdrive",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Elevated",
            slug: "elevated",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Elevated 2",
            slug: "elevated-2",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Embers",
            slug: "embers",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Embers 2",
            slug: "embers-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Estrella",
            slug: "estrella",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fantasy",
            slug: "fantasy",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fatal Temple",
            slug: "fatal-temple",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Feral Paradise",
            slug: "feral-paradise",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fissura",
            slug: "fissura",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "FlagTest",
            slug: "flagtest",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Flaque",
            slug: "flaque",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Freezing Point",
            slug: "freezing-point",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Formorgar",
            slug: "formorgar",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Formorgar 2",
            slug: "formorgar-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fort Aqua",
            slug: "fort-aqua",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fossil Canyon",
            slug: "fossil-canyon",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fossil5CP",
            slug: "fossil5cp",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fridgidus",
            slug: "fridgidus",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Frostbite",
            slug: "frostbite",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Grasslands",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Grasslands KOTH",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Greenwoods",
            slug: "greenwoods",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Halcyon",
            slug: "halcyon",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Haunted Hallows",
            slug: "haunted-hallows",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Hell Bound",
            slug: "hell-bound",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Hold Fast",
            slug: "hold-fast",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Homestead",
            slug: "Homestead",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Illegal Office",
            slug: "illegal-office",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Industrial",
            slug: "industrial",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Infernus",
            slug: "infernus",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Injustice",
            slug: "injustice",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Jungletree Bazooka",
            slug: "jungletree-bazooka",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Justice 1",
            slug: "justice-1",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Justice 2",
            slug: "justice-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Justice 3",
            slug: "justice-3",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Knuckles and Goggles",
            slug: "kluckles-and-goggles",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "La Cove",
            slug: "la-cove",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Launch",
            slug: "launch",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Luar Remastered",
            slug: "luar-remastered",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Maisosen",
            slug: "maisosen",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mirage",
            slug: "mirage",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mulvis",
            slug: "mulvis",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mute City 1",
            slug: "mute-city-1",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mute City 2",
            slug: "mute-city-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mute City 3",
            slug: "mute-city-3",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mynera",
            slug: "mynera",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mystic",
            slug: "mystic",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Nautica",
            slug: "nautica",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "New Heaven",
            slug: "new-heaven",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "New World",
            slug: "new-world",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Nordic Holiday",
            slug: "nordic-holiday",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Obelis",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Operation: Desert Storm",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Operation: Desert Storm CTF",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Operation: Winter Storm",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Operation: Winter Storm HC",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Outbreak",
            slug: "outbreak",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Palm Rust",
            slug: "palm-rust",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Parkour: Debris",
            slug: "parkour-debris",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Plaza TE",
            slug: "plaza-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ponylands 2",
            slug: "ponylands-2",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Port Town",
            slug: "port-town",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Port Town 2",
            slug: "port-town-2",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Presta",
            slug: "presta",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Quarry",
            slug: "quarry",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Quintus",
            slug: "quintus",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Quintus: Origins",
            slug: "quintus-origins",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ranch Raid",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Raptors",
            slug: "raptors",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous",
            slug: "rendezvous",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous 2k17",
            slug: "rendezvous-2k17",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous 3",
            slug: "rendezvous-3",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous 3 TE",
            slug: "rendezvous-3-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous Champions",
            slug: "rendezvous-champions",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous CTW",
            slug: "rendezvous-ctw",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous Meadows",
            slug: "rendezvous-meadows",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous Redux",
            slug: "rendezvous-redux",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Requisite TE",
            slug: "requisite-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rigor Mortis",
            slug: "rigor-mortis",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rocky Pastures",
            slug: "rocky-pastures",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rolexius",
            slug: "rolexius",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Salvo",
            slug: "salvo",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Salzburg",
            slug: "salzburg",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Salzburg 2",
            slug: "salzburg-2",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Sandstorm",
            slug: "sandstorm",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Sector Six",
            slug: "sector-six",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Scaffold",
            slug: "scaffold",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Scizor",
            slug: "scizor",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex",
            slug: "senex",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex 2",
            slug: "senex-2",
            game_mode: "DTM",
            record_first: [ { player_name: "Xuph", player_uuid: "9116d3fa-1400-4ada-aecd-2eae1d73e383", distance: "143.63", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex 3",
            slug: "senex-3",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex Competitive",
            slug: "senex-competitive",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex CTW",
            slug: "senex-ctw",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex Scrim",
            slug: "senex-scrim",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Shadient",
            slug: "shadient",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Shadow Forest",
            slug: "shadow-forest",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Silent as Violent",
            slug: "silent-as-violent",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Simon",
            slug: "simon",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Solitz",
            slug: "solitz",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Spore",
            slug: "spore",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Squared Nature",
            slug: "squared-nature",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Starshine Beach",
            slug: "starshine-beach",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Static",
            slug: "static",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "StoneShock(5CP)",
            slug: "stoneshock5cp",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Strike TE",
            slug: "strike-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Sunbeam Temple",
            slug: "sunbeam-temple",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Supply",
            slug: "supply",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Supply: Frenzy",
            slug: "supply-frenzy",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Susanoo",
            slug: "susanoo",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Swamp Lands",
            slug: "",
            game_mode: "Skywars",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Sweet Slopes",
            slug: "sweet-slopes",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Tasty Fight",
            slug: "tasty-fight",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ternio",
            slug: "ternio",
            game_mode: "DTM",
            record_first: [ { player_name: "Tynvale", player_uuid: "2c937226-9ed3-4adc-9a0e-9747aeee1220", distance: "77.42", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Terra CTF",
            slug: "terra-ctf",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "The Badlands",
            slug: "the-badlands",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "The Hallow",
            slug: "the-hallow",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "The Toys",
            slug: "the-toys",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Titans",
            slug: "titans",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Tree Frog",
            slug: "tree-frog",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Twilight: Mars",
            slug: "twilight-mars",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "U-Bahn",
            slug: "u-bahn",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Unix",
            slug: "unix",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Vallis",
            slug: "vallis",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Vendetta",
            slug: "Vendetta",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Venomous",
            slug: "venomous",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Venomous Nexus",
            slug: "venomous-nexus",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Volcano",
            slug: "volcano",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Volcano: Turmoil",
            slug: "volcano-turmoil",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Wahiz Competitive",
            slug: "wahiz-competitive",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Wahiz CTW",
            slug: "wahiz-ctw",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Winters Day TE",
            slug: "winters-day-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Wonderland",
            slug: "wonderland",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Wool Terrace",
            slug: "wool-terrace",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Worlds End",
            slug: "worlds-end",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Yellowstone",
            slug: "yellowstone",
            game_mode: "DTM",
            record_first: [ { player_name: "Crazy_", player_uuid: "a9f11454-beac-4cc3-a138-1780802c8794", distance: "23.6", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "YingYang",
            slug: "yingyang",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Xena TE",
            slug: "xena-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Zalidor",
            slug: "zalidor",
            game_mode: "DTM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Zao",
            slug: "zao",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, ],
    };
    var output = template(data);
    document.getElementById("records-output").innerHTML = output;
}
