window.onload = function() {
    var source = document.getElementById("records-template").innerHTML;
    var template = Handlebars.compile(source);
    var data = {
        records: [ {
            map: "Actrix",
            slug: "actrix",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Actrix TE",
            slug: "actrix-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ambush TE",
            slug: "ambush-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ancient Lake",
            slug: "ancient-lake",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arc",
            slug: "arc",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arcadia TE",
            slug: "arcadia-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arizona",
            slug: "arizona",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arkashia",
            slug: "arkashia",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Arriva",
            slug: "arriva",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Asylum",
            slug: "asylum",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Audax",
            slug: "audax",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Aura",
            slug: "aura",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Babylon Gardens",
            slug: "babylon-gardens",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Block Fort",
            slug: "block-fort",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Bob-omb Battlefield",
            slug: "bob-omb-battlefield",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boolean 1",
            slug: "boolean-1",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boolean Classic",
            slug: "boolean-classic",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boolean TE",
            slug: "boolean-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Boundaries TE",
            slug: "boundaries-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Camel",
            slug: "camel",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Campfire",
            slug: "campfire",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Campus",
            slug: "campus",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Canyon",
            slug: "canyon",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Castella",
            slug: "castella",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Castle Adventure TE",
            slug: "castle-adventure-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Chimeric",
            slug: "chimeric",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "ChimericIIITrio",
            slug: "chimericiiitrio",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Chowder",
            slug: "chowder",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "City Scape",
            slug: "city-scape",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Civilization",
            slug: "civilization",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Cobweb Hills",
            slug: "cobweb-hills",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "ColorExplosion",
            slug: "colorexplosion",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Coniculum",
            slug: "coniculum",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Crossfire TE",
            slug: "crossfire-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Cruhan",
            slug: "cruhan",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dirilis",
            slug: "dirilis",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dragonblaze Peaks",
            slug: "dragonblaze-peaks",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dragons Den",
            slug: "dragons-den",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dredmor",
            slug: "dredmor",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Drought Stand",
            slug: "drought-stand",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Dustdrive",
            slug: "dustdrive",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Elevated",
            slug: "elevated",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Elevated 2",
            slug: "elevated-2",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Estrella",
            slug: "estrella",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fatal Temple",
            slug: "fatal-temple",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Feral Paradise",
            slug: "feral-paradise",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "FlagTest",
            slug: "flagtest",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Flaque",
            slug: "flaque",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Freezing Point",
            slug: "freezing-point",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fossil5CP",
            slug: "fossil5cp",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Fridgidus",
            slug: "fridgidus",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Greenwoods",
            slug: "greenwoods",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Hell Bound",
            slug: "hell-bound",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Hold Fast",
            slug: "hold-fast",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Homestead",
            slug: "Homestead",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Illegal Office",
            slug: "illegal-office",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Industrial",
            slug: "industrial",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Injustice",
            slug: "injustice",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Justice 3",
            slug: "justice-3",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Knuckles and Goggles",
            slug: "kluckles-and-goggles",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "La Cove",
            slug: "la-cove",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Launch",
            slug: "launch",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mirage",
            slug: "mirage",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mulvis",
            slug: "mulvis",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Mynera",
            slug: "mynera",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Nautica",
            slug: "nautica",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "New Heaven",
            slug: "new-heaven",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "New World",
            slug: "new-world",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Outbreak",
            slug: "outbreak",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Parkour: Debris",
            slug: "parkour-debris",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Plaza TE",
            slug: "plaza-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Ponylands 2",
            slug: "ponylands-2",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Presta",
            slug: "presta",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Quarry",
            slug: "quarry",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Raptors",
            slug: "raptors",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous 2k17",
            slug: "rendezvous-2k17",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous 3 TE",
            slug: "rendezvous-3-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous Champions",
            slug: "rendezvous-champions",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous CTW",
            slug: "rendezvous-ctw",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rendezvous Meadows",
            slug: "rendezvous-meadows",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Requisite TE",
            slug: "requisite-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rocky Pastures",
            slug: "rocky-pastures",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Rolexius",
            slug: "rolexius",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Salvo",
            slug: "salvo",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Salzburg",
            slug: "salzburg",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Salzburg 2",
            slug: "salzburg-2",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Scaffold",
            slug: "scaffold",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Scizor",
            slug: "scizor",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex Competitive",
            slug: "senex-competitive",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex CTW",
            slug: "senex-ctw",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Senex Scrim",
            slug: "senex-scrim",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Shadient",
            slug: "shadient",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Silent as Violent",
            slug: "silent-as-violent",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Simon",
            slug: "simon",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Solitz",
            slug: "solitz",
            game_mode: "Arcade",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Spore",
            slug: "spore",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Static",
            slug: "static",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "StoneShock(5CP)",
            slug: "stoneshock5cp",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Strike TE",
            slug: "strike-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Supply",
            slug: "supply",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Supply: Frenzy",
            slug: "supply-frenzy",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Sweet Slopes",
            slug: "sweet-slopes",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Terra CTF",
            slug: "terra-ctf",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "The Badlands",
            slug: "the-badlands",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "The Toys",
            slug: "the-toys",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Titans",
            slug: "titans",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Tree Frog",
            slug: "tree-frog",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Twilight: Mars",
            slug: "twilight-mars",
            game_mode: "Frenzy",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "U-Bahn",
            slug: "u-bahn",
            game_mode: "KOTH",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Vallis",
            slug: "vallis",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Vendetta",
            slug: "Vendetta",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Venomous Nexus",
            slug: "venomous-nexus",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Volcano: Turmoil",
            slug: "volcano-turmoil",
            game_mode: "DTC",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Wahiz Competitive",
            slug: "wahiz-competitive",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Wahiz CTW",
            slug: "wahiz-ctw",
            game_mode: "CTW",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Winters Day TE",
            slug: "winters-day-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Wool Terrace",
            slug: "wool-terrace",
            game_mode: "CTF",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Worlds End",
            slug: "worlds-end",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Xena TE",
            slug: "xena-te",
            game_mode: "Tournament",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, {
            map: "Zao",
            slug: "zao",
            game_mode: "TDM",
            record_first: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_second: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
            record_third: [ { player_name: "", player_uuid: "", distance: "", evidence: ""} ],
        }, ],
    };
    var output = template(data);
    document.getElementById("records-output").innerHTML = output;
}
