name: build

on:
  push:
    branches: source
  pull_request:
    branches: source
  repository_dispatch:
    types:
      - run_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/uuid-resolver/requirements.txt

      - name: execute py script
        run: |
          python ./scripts/uuid-resolver/run.py ./src/data/maps ./src/data/uuids.json

      - name: commit changes
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update global UUID data file
          branch: source
          file_pattern: src/data/*.json
          commit_user_name: MCResourcePile
          commit_user_email: MCResourcePile@gmail.com
          commit_author: MCResourcePile <MCResourcePile@gmail.com>

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: install ruby dependencies
        run: |
          npm install
          gem install sass

      - name: build static pages
        run: grunt

      - name: deploy to github pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: source
          BRANCH: master
          FOLDER: out
          CLEAN: true
          GIT_CONFIG_EMAIL: MCResourcePile@gmail.com
          COMMIT_MESSAGE: Deploy to GitHub Pages - ${{ github.sha }}
