name: build

on:
  push:
    branches: source
  pull_request:
    branches: source
  repository_dispatch:
    types:
      - run_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: checkout name fetcher
        uses: actions/checkout@v4
        with:
          repository: MCResourcePile/name-fetcher
          path: "./scripts/name-fetcher"

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.1'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/name-fetcher/requirements.txt

      - name: execute py script
        run: |
          python ./scripts/name-fetcher/run.py ./src/data ./src/data/uuids.json

      - name: remove temp files
        run: |
          rm -r ./scripts

      - name: commit changes
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update global UUID data file
          branch: source
          file_pattern: src/data/*.json
          commit_user_name: MCResourcePile
          commit_user_email: MCResourcePile@gmail.com
          commit_author: MCResourcePile <MCResourcePile@gmail.com>

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: install ruby dependencies
        run: |
          npm install
          gem install sass

      - name: build static pages
        run: grunt

      - name: deploy to github pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          folder: out
          clean: true
          git-config-email: MCResourcePile@gmail.com
          commit-message: Deploy to GitHub Pages - ${{ github.sha }}
