name: fetch-uuids

on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:

jobs:
  fetch-uuids:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # - name: checkout name fetcher 
      #   uses: actions/checkout@v3
      #   with:
      #     repository: MCResourcePile/name-fetcher
      #     path: scripts/name-fetcher
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/uuid-resolver/requirements.txt
      
      - name: execute py script
        run: |
          python ./scripts/uuid-resolver/run.py ./src/data ./src/data/uuids.json --force

      - name: commit changes
        if: github.event_name != 'pull_request'
        uses: EndBug/add-and-commit@v9
        with:
          message: Update global UUID data file

      - uses: actions/upload-artifact@v3
        with:
          name: uuids.json
          path: ./src/data/uuids.json
