name: uuids

on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/uuid-resolver/requirements.txt
          
      - name: execute py script
        run: |
          python ./scripts/uuid-resolver/run.py ./src/data/maps ./src/data/uuids.json --force
          
      - name: commit changes
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update global UUID data file
          branch: source
          file_pattern: src/data/*.json
          commit_user_name: MCResourcePile
          commit_user_email: MCResourcePile@gmail.com
          commit_author: MCResourcePile <MCResourcePile@gmail.com>       
